version: '3'
services:
  son-mongo:
    image: mongo
    container_name: son-mongo
    ports:
        - 27017:27017
    restart: always
  son-broker:
    image: rabbitmq:3
    ports:
     - "5672:5672"
     - "15672:15672"
    container_name: son-broker
    restart: always
  tng-policy-mngr:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - son-mongo
    restart: always

